version: "3.7"
services: 

    server:
        build: ./resources/server
        container_name: "musicbrainz_server"
        depends_on:
            - redis
            - db
        restart: unless-stopped
        command: ls
        volumes:
            - ./musicbrainz_server:/musicbrainz
        entrypoint: [ "ls", "-a" ]
        ports: 
            - "5000:5000"
        networks:
            - MBNet

    db:
        build: ./resources/database
        container_name: "postgres"
        volumes:
            - type: volume
              source: db-data
              target: /var/lib/postgresql/data
        networks:
            - MBNet

    redis:
        image: redis
        container_name: "redis"
        networks:
            - MBNet

networks:
    MBNet:

volumes:
    db-data: