FROM postgres:10

ENV POSTGRES_HOST_AUTH_METHOD=trust

RUN apt-get update
RUN apt-get install git-core -y
RUN apt-get install build-essential -y
RUN apt-get install \
    postgresql-10 \
    postgresql-contrib-10 \
    postgresql-server-dev-10 -y
RUN apt-get install \
    libicu-dev \
    pkg-config -y
RUN git clone https://github.com/metabrainz/postgresql-musicbrainz-collate
RUN git clone https://github.com/metabrainz/postgresql-musicbrainz-unaccent
WORKDIR /postgresql-musicbrainz-unaccent
RUN make && make install
WORKDIR /postgresql-musicbrainz-collate
RUN make && make install
